sudo: required
language: node_js
node_js:
  - "6"

services:
  - docker

branches:
  only:
    - master

cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build:heroku-docker
  - docker build -t registry.heroku.com/freibier-homepage/web .
after_success:
  - echo "$TRAVIS_BRANCH"
  - echo "$TRAVIS_PULL_REQUEST"
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com;
    docker push registry.heroku.com/freibier-homepage/web;
    fi
